ManageProject/Controllers/ManageUserProjectController.cs
using log4net;
using ManageProject.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ManageProject.DAL;
using ManageProject.DAL.NUoW;

namespace ManageProject.Controllers
{
    [Authorize(Roles = "Admin,PM")]
    public class ManageUserProjectController : Controller
    {
        private static readonly ILog logger = LogManager.GetLogger(

        System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        ApplicationDbContext db = new ApplicationDbContext();
        GenericUnitOfWork unitOfWork = new GenericUnitOfWork();
        // GET: ManageIProject
        public ActionResult Index()
        {
            var model = unitOfWork.Repository<UserProject>().Get().Where(x => x.Disable == false).ToList();
            return View(model);
        }
        public ActionResult Create(string IdUser)
        {
            if(User.IsInRole("Admin"))
            {
                ViewBag.ListProject = new SelectList(unitOfWork.Repository<ManageProjects>().Get().Where(x => x.IsDelete == false).ToList(), "Project", "ProjectName");
                ViewBag.ListUser = new SelectList(db.Users.ToList(),"Id", "UserName");
                ViewBag.Task = new SelectList(db.Roles.Where(x => x.Name != "Admin").ToList(), "Name", "Name");
                return View();
            }
            else if ((ManagerRolesController.IsDenied(IdUser)&& User.IsInRole("PM")))
            {
                var tmp = unitOfWork.Repository<UserProject>().Get(filter: s => s.UserId == IdUser, includeProperties: "managerProject").Select(s => s.managerProject).Distinct();
                ViewBag.ListProject = new SelectList(tmp.ToList(),"Project", "ProjectName");
                ViewBag.ListUser = new SelectList(db.Users.ToList(),"Id", "UserName");
                ViewBag.Task = new SelectList(db.Roles.Where(x=>x.Name!="Admin").ToList(), "Name", "Name");
                return View();
            }
            
            else
            {
                logger.Info("Create Task fail!!");
                SetAlert("Bạn không có quyền truy cập", "error");
               return RedirectToAction("Index");
            }
          
        }
        /// <summary>
        /// Create UserProject
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Project,UserId,Disable,TaskUser,PositionUser,Notes,Updatedate,Updateby,Createdate,Createby,Deletedate,Deleteby,IsDelete")] UserProject userProject)
        {

            var isTask = unitOfWork.Repository<UserProject>().Get().Where(x => x.Project == userProject.Project && x.UserId == userProject.UserId).SingleOrDefault();
            if (isTask != null && isTask.Disable == true)
            {
                unitOfWork.Repository<UserProject>().Delete2(isTask.Project, isTask.UserId);
                userProject.Createby = User.Identity.Name;
                userProject.Createdate = Convert.ToDateTime(DateTime.Now);
                unitOfWork.Repository<UserProject>().Insert(userProject);
                unitOfWork.Save();
                SetAlert("Update Successfully", "success");
                return RedirectToAction("Index");
            }
            else if (isTask != null)
            {
                SetAlert("User is already exist!", "error");
                return Redirect(Request.UrlReferrer.ToString());
            }
                
            try
            {
                if (ModelState.IsValid)
                {
                    userProject.Createby = User.Identity.Name;
                    userProject.Createdate = Convert.ToDateTime(DateTime.Now);
                    unitOfWork.Repository<UserProject>().Insert(userProject);
                    unitOfWork.Save();
                    SetAlert("Update Successfully", "success");
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                SetAlert("Update Error", "error");
                logger.ErrorFormat("Errors:{0}", ex.Message);
                ModelState.AddModelError("", ex.Message);
            }
            return View(userProject);
        }
        /// <summary>
        /// Edit table UserProject
        /// </summary>
        /// <param name="UserId"></param>
        /// <param name="ProjectId"></param>
        /// <param name="IdUser"></param>
        /// <returns></returns>
        public ActionResult Edit(string UserId, string id,string IdUser)
        {
            var model = unitOfWork.Repository<UserProject>().Get().Where(x => x.Project == id && x.UserId == UserId).FirstOrDefault();
            ViewBag.Task = new SelectList(db.Roles.Where(x => x.Name != "Admin").ToList(), "Name", "Name");

            if (User.IsInRole("Admin") ||(User.IsInRole("PM") && ManagerRolesController.IsDenied(IdUser, id)) )
            {
                if(model == null)
                {
                    var userproject = new UserProject
                    {
                        Project = id,
                        UserId = UserId
                    };
                    return View(userproject);
                }
                return View(model);
            }
            else
            {
        
                SetAlert("Bạn không có quyền", "error");
                return RedirectToAction("Index");
            }
           
            
        }
        /// <summary>
        /// Edit table UserProject -method Post
        /// </summary>
        /// <param name="project"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Project,UserId,Disable,TaskUser,PositionUser,Notes,Updatedate,Updateby,Createdate,Createby,Deletedate,Deleteby,IsDelete")] UserProject userProject)
        {
            var model = unitOfWork.Repository<UserProject>().Get().Where(x => x.Project == userProject.Project && x.UserId == userProject.UserId).SingleOrDefault();
            try
            {
                if (model !=null && ModelState.IsValid)
                {
                    model.Updateby = User.Identity.Name;
                    model.Updatedate = Convert.ToDateTime(DateTime.Now);
                    model.TaskUser = userProject.TaskUser;
                    model.PositionUser = userProject.PositionUser;
                    model.Disable = false;
                    unitOfWork.Save();
                }
                if(model==null)
                {
                    unitOfWork.Repository<UserProject>().Insert(userProject);
                    unitOfWork.Save();
                }
                SetAlert("Update successfully", "success");
                return Redirect(Request.UrlReferrer.ToString());
            }
            catch (Exception ex)
            {
                logger.Error(ex.Message);
                SetAlert("Update Error", "error");
                ModelState.AddModelError("", ex.Message);
            }
            return View(model);

        }

        /// <summary>
        /// Delete value table UserProject
        /// </summary>
        /// <param name="UserId"></param>
        /// <param name="ProjectId"></param>
        /// <param name="IdUser"></param>
        /// <returns></returns>
        public ActionResult Delete(string UserId,string ProjectId,string IdUser)
        {
            var model = unitOfWork.Repository<UserProject>().Get().Where(m => m.Project == ProjectId && m.UserId == UserId).SingleOrDefault();
            if (User.IsInRole("Admin")||(User.IsInRole("PM") && ManagerRolesController.IsDenied(IdUser,ProjectId)))
            {
                return View(model);
            }
            else
            {
                SetAlert("Bạn không có quyền!", "error");
                return RedirectToAction("Index");
            }
            
            
        }
        /// <summary>
        /// Delete User 
        /// </summary>
        /// <param name="UserId"></param>
        /// <param name="ProjectId"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult ComfirmDelete(string UserId, string ProjectId)
        {
            var model = unitOfWork.Repository<UserProject>().Get().Where(m => m.Project == ProjectId && m.UserId == UserId).SingleOrDefault();
            try
            {
                if (ModelState.IsValid)
                {
                    model.Deleteby = User.Identity.Name;
                    model.Deletedate = Convert.ToDateTime(DateTime.Now);
                    model.IsDelete = true;
                    unitOfWork.Save();
                    SetAlert("Update success", "success");
                    return Redirect(Request.UrlReferrer.ToString());
                }
                
            }
            catch (Exception ex)
            {
                logger.Error(ex.Message);
                SetAlert("Update Error", "error");
                ModelState.AddModelError("", ex.Message);
            }
            return RedirectToAction("Index");

        }

        /// <summary>
        /// Info table UserProject
        /// </summary>
        /// <param name="UserId"></param>
        /// <param name="ProjectId"></param>
        /// <returns></returns>
        public ActionResult Details(string UserId, string id)
        {
            var model = unitOfWork.Repository<UserProject>().Get().Where(m => m.Project == id && m.UserId == UserId).SingleOrDefault();
            return View(model);

        }

        /// <summary>
        /// Info User
        /// </summary>
        /// <param name="UserId"></param>
        /// <returns></returns>
        public ActionResult InfoUser(string UserId)
        {

ManageProject/Views/ManageUserProject/Create.cshtml
@model ManageProject.Models.UserProject
@{
    ViewBag.Title = "Create User for Project";
   
}

<h2>@ViewBag.Title.</h2>

<div id="create">

    @using (Html.BeginForm("Create", "ManageUserProject", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="row hidedata" id="hidDiv">
            <div class="">
                <form class="form">

                    <div class="form-group">
                        <div class="col-sm-3">
                            <label for="ProjectId" class="control-label">Project Name:</label>*
                        </div>

                        <div class="col-sm-9">

                            @Html.DropDownListFor(model => model.Project, ViewBag.ListProject as SelectList, "--Select--", htmlAttributes: new { @class = "form-control", @required = "required", @oninvalid = "this.setCustomValidity('The field is required')", @oninput = "setCustomValidity('')" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3 ">
                            <label for="UserId" class="control-label">User Name:</label>*
                        </div>

                        <div class="col-sm-9">
                            @Html.DropDownListFor(model => model.UserId, ViewBag.ListUser as SelectList, "--Select--", htmlAttributes: new { @class = "form-control", @required = "required", @oninvalid = "this.setCustomValidity('The field is required')", @oninput = "setCustomValidity('')" })

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-3">
                            <label for="TaskUser" class="control-label">Task User:</label>*
                        </div>

                        <div class="col-sm-9">
                          
                            @Html.DropDownListFor(model => model.TaskUser, ViewBag.Task as SelectList, "--Select--", htmlAttributes: new { @class = "form-control", @required = "required", @oninvalid = "this.setCustomValidity('The field is required')", @oninput = "setCustomValidity('')" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3">
                            <label for="PositionUser" class="control-label">Position User:</label>*
                        </div>

                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="PositionUser" required oninvalid = "this.setCustomValidity('The field is required')" oninput = "setCustomValidity('')">

                        </div>
                    </div>



                    <div class="form-group">
                        <div class="col-sm-3"></div>
                        <div class="col-sm-9">
                            <button type="submit" class="btn" style="background-color:green;color:white">Create</button>
                            
                        </div>
                    </div>

                </form>

            </div>
        </div>
    }

</div>
<div>
    <a href="@Request.UrlReferrer" class="btn btn-sm btn-primary">Back to List</a>
</div>
@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
}

ManageProject/Views/ManageUserProject/Delete.cshtml
@model ManageProject.Models.UserProject

@{

    ViewBag.Title = "Delete Task";

    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="row">

    <div class="col-sm-12">

        <h2>@ViewBag.Title</h2>

        <hr />

        <div class="text-center">

            <h5>Do you sure want to delete Task of member in this project?</h5>

            @using (Html.BeginForm())

            {

                @Html.AntiForgeryToken()

                @Html.ValidationSummary("", new { @class = "text-danger" })

                <button type="submit" class="btn btn-primary">Accept</button>
                
                <a href="@Request.UrlReferrer" class="btn btn-sm btn-primary">Cancel</a>

            }

        </div>

    </div>

</div>

ManageProject/Views/ManageUserProject/Details.cshtml
@model ManageProject.Models.UserProject

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div id="details">
    <div>

        <table class=" table table-bordered" style="background-color:lightgreen">
            <tr>
                <td><strong>Project Name</strong></td>
                <td>@Model.managerProject.ProjectName</td>
            </tr>
            <tr>
                <td><strong>UserName</strong></td>
                <td>@Model.manageUser.UserName</td>
            </tr>
            <tr>
                <td><strong>Task User</strong></td>
                <td>@Model.TaskUser</td>
            </tr>
            <tr>
                <td><strong>Position User</strong></td>
                <td>@Model.PositionUser</td>
            </tr>
            <tr>
                <td><strong>Create Date</strong></td>
                <td class="text-center " style="font-size:smaller;color:black"><strong>@Model.Createby</strong>  <br /><strong> @Model.Createdate</strong> </td>

            </tr>
            <tr>
                <td><strong>Update Date</strong></td>
                <td class="text-center" style="font-size:smaller;color:black"><strong>@Model.Updateby</strong>  <br /><strong>@Model.Updatedate</strong> </td>

            </tr>
        </table>
        
    </div>
   
</div>
<div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { ProjectId = Model.Project, UserId = Model.UserId }, new { @class = "btn btn-success" })
       
    </p>
    <a href="@Request.UrlReferrer" class="btn btn-sm btn-primary">Back to List</a>
</div>

ManageProject/Views/ManageUserProject/Edit.cshtml
@model ManageProject.Models.UserProject

@{
    ViewBag.Title = "Edit Task";
}

<h2>Edit</h2>
<div id="edit">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(Model => Model.Project)

        @Html.HiddenFor(Model => Model.UserId)

        <div class="form-group">
            @Html.LabelFor(model => model.TaskUser, "Task User", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">

                @Html.DropDownListFor(model => model.TaskUser, ViewBag.Task as SelectList, "--Select--", htmlAttributes: new { @class = "form-control", @required = "required", @oninvalid = "this.setCustomValidity('The field is required')", @oninput = "setCustomValidity('')" })

                @Html.ValidationMessageFor(model => model.TaskUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group  ">
            @Html.LabelFor(model => model.PositionUser, "Position User", htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.TextAreaFor(model => model.PositionUser, htmlAttributes: new { @class = "form-control", @required = "required", @oninvalid = "this.setCustomValidity('The field is required')", @oninput = "setCustomValidity('')" })

                @Html.ValidationMessageFor(model => model.PositionUser, "", new { @class = "text-danger" })
                @Html.HiddenFor(Model => Model.Createby)
                @Html.HiddenFor(Model => Model.Createdate)
                @Html.HiddenFor(Model => Model.Deleteby)
                @Html.HiddenFor(Model => Model.Deletedate)
                @Html.HiddenFor(Model => Model.IsDelete)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <input type="submit" value="Save" class="btn" style="background-color:green;color:white" />
            </div>
        </div>
    </div>
    }
</div>
<div>
   
    <a href="@Request.UrlReferrer" class="btn btn-sm btn-primary">Back to List</a>
</div>

ManageProject/Views/ManageUserProject/Index.cshtml
@using ManageProject.Models
@using Microsoft.AspNet.Identity
@model IEnumerable<UserProject>
@{       
                ViewBag.Title = "Member In Projects";

                Layout = "~/Views/Shared/_Layout.cshtml";
                ApplicationDbContext db = new ApplicationDbContext();
                var id = User.Identity.GetUserId();
                bool checkRoles(string ProjectId)
                {
                    var tmp = db.UserProjects.Where(x => x.Project == ProjectId && x.Disable == false && x.UserId == id).ToList();
                    if (tmp.Count > 0)
                    {
                        return true;
                    }
                    return false;

                }
}

<h2>@ViewBag.Title</h2>

<hr />
@if (User.IsInRole("Admin") || (User.IsInRole("PM")))
{
    <button class="btn" id="btncreate"style="background-color:green;color:white" IdUser="@User.Identity.GetUserId()" data-toggle="modal" data-target="#myModal">Create</button>

}
    <p></p>

<table class="table table-bordered table-hover table-striped"  id="myTable">

    <thead style="background-color:forestgreen;color:white">

        <tr>
            <th>Project Name</th>

            <th>User Name</th>

            <th>Task User</th>

            <th>Position User </th>

            <th></th>
        </tr>

    </thead>

    <tbody>

        @foreach (var item in Model)
        {

        <tr>

            <td>@item.managerProject.ProjectName</td>

                <td>@Html.ActionLink(@item.manageUser.UserName, "InfoUser", new { UserId = item.UserId }) </td>

                <td>@item.TaskUser</td>

                <td>@item.PositionUser</td>
                
                <td class="text-center col-md-4">
                    @if (User.IsInRole("Admin") || (User.IsInRole("PM") && checkRoles(item.Project)))
                    {
                        @Html.Raw(@Html.Label("[replacetext]", new { id = item.Project, UserId = item.UserId, IdUser = User.Identity.GetUserId(), @style = "cursor:pointer", @class = "btnEdit" }).ToHtmlString().Replace("[replacetext]", "<img src=\"/Content/ima/Edit.ico\" height=\"30\">"))
                        @Html.Raw(@Html.Label("[replacetext]", new { id = item.Project, UserId = item.UserId, IdUser = User.Identity.GetUserId(), @class = "btnDetail", @style = "cursor:pointer" }).ToHtmlString().Replace("[replacetext]", "<img src=\"/Content/ima/My-Documents.png\" height=\"30\">"))
                        @Html.Raw(@Html.ActionLink("[replacetext]", "Delete", new { id = item.Project, UserId = item.UserId, IdUser = User.Identity.GetUserId(), @style = "cursor:pointer" }, new { UserId = item.UserId, id = item.Project, @class = "btndelete" }).ToHtmlString().Replace("[replacetext]", "<img src=\"/Content/ima/Recycle.png\" height=\"30\">"))

                    }
                    else
                    {
                        <button disabled class="btn btn-sm btn-success" style="background-color:darkgray">  <img height="20" src="~/Content/ima/Recycle.png" /></button>
                        <button disabled class="btn btn-sm btn-success" style="background-color:darkgray">  <img height="20" src="~/Content/ima/Edit.ico" /></button>
                        <button disabled class="btn btn-sm btn-success" style="background-color:darkgray">  <img height="20" src="~/Content/ima/My-Documents.png" /></button>

                    }


                </td>

            </tr>

        }

    </tbody>

</table>



<div id="myModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color:forestgreen;color:white">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Create Project User</h4>
            </div>
            <div class="modal-body">
                <div class="dialog1 ">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" style="background-color:gray;color:white" class="btn" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
@section Scripts{

    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();

            $('.btndelete').click(function (e) {
                var id = $(this).attr('id');
                var userid = $(this).attr('UserId');
                console.log(id);
                $.confirm({
                    title: 'Message',
                    content: 'Do you want to delete ?',
                    buttons: {
                        Delete: function () {
                            $.ajax({
                                type: "POST",
                                url: "/ManageUserProject/DeleteUserProject",
                                data: { 'UserId': userid, 'id': id },
                                dataType: "json",
                                success: function (response) {
                                    console.log(response);
                                    if (response) {
                                        $.alert("Update success");
                                        console.log(response);
                                        location.reload();
                                    }
                                    else {
                                        $.alert("Update Error");
                                    }
                                },
                            });
                        },
                        cancel: function () {

                        },
                    }
                });
                e.preventDefault();
            });

            $('#btncreate').click(function (e) {

                var id = $(this).attr('IdUser');
                $('.modal-body').load("/ManageUserProject/Create #create", "IdUser=" + id + "", function (response) {
                    this; // dom element

                });
                e.preventDefault();
            });
            //Btn detail
            $('.btnDetail').attr("data-toggle", "modal");
            $('.btnDetail').attr("data-target", "#myModal");
            $('.btnDetail').click(function (e) {
                var userid = $(this).attr('UserId');
                var id = $(this).attr('id');
                $('.modal-body').load("/ManageUserProject/Details #details", "UserId=" + userid + "&id=" + id + "", function (response) {

                    this; // dom element

                });
                e.preventDefault();

            });

            //Btn Edit
            $('.btnEdit').attr("data-toggle", "modal");
            $('.btnEdit').attr("data-target", "#myModal");
            $('.btnEdit').click(function (e) {
                var userid = $(this).attr('UserId');
                var id = $(this).attr('id');
                var iduser = $(this).attr('IdUser');
                $('.modal-body').load("/ManageUserProject/Edit #edit", "UserId=" + userid + "&id=" + id + "&IdUser=" + iduser + "", function (response) {

                    this; // dom element

                });
                e.preventDefault();

            });
        });
    </script>
    <script>

    </script>


}

ManageProject/Views/ManageUserProject/InfoUser.cshtml
@using ManageProject.Models
@using Microsoft.AspNet.Identity
@model IEnumerable<UserProject>
@{
    ViewBag.Title = "InfoUser";
}

<h2>Info User </h2>

<table class="table table-bordered table-hover table-striped" id="myTable">
    <thead style="background-color:forestgreen;color:white">
        <tr>
            <th>UserName</th>
            <th>ProjectName</th>
            <th>Status</th>
            <th>Task User</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.manageUser.UserName</td>
                <td>@item.managerProject.ProjectName</td>
                <td>
                    <b class="text-danger">@item.managerProject.isJoin  </b>

                </td>
                <td class="text-success"><b>@item.TaskUser</b></td>
            </tr>
        }
    </tbody>
</table>
<a href="@Request.UrlReferrer" class="btn btn-primary">Back to List</a>
<link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
@section Scripts{

    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>


}